# Generated by Django 3.1.7 on 2021-02-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
