# Generated by Django 3.1.7 on 2021-02-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_app', '0004_auto_20210219_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycustomuser',
            name='age',
            field=models.IntegerField(default=15, null=True),
        ),
    ]
