# Generated by Django 3.1.7 on 2021-02-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_app', '0007_mycustomuser_homepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycustomuser',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='mycustomuser',
            old_name='display_name',
            new_name='Display_name',
        ),
        migrations.RenameField(
            model_name='mycustomuser',
            old_name='homepage',
            new_name='Homepage',
        ),
    ]
